apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/helm-chart-4.3.0/deploy/static/provider/baremetal/deploy.yaml
patchesStrategicMerge:
- ingress-nginx-v1.4.0.yml.patch

