apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: blog
        image: ghcr.io/erebe/blog:latest
        imagePullPolicy: Always
        args: ["serve", "--interface", "0.0.0.0", "--port", "8087"]
        ports:
        - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 8087
  clusterIP: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - blog.erebe.dev
    secretName: blog-tls
  rules:
  - host: blog.erebe.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: blog
          servicePort: 8087
